apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oaqx7dhs7-python
  janus-idp.io/tekton: oaqx7dhs7-python
  backstage.io/kubernetes-id: oaqx7dhs7-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oaqx7dhs7-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
